{"origin": "/home/a08test/submissions/adebayob/a2", "assignment": "a2", "students": [{"last": "Adebayo", "section": "N/A", "first": "Babatope", "email": "tope.adebayo@mail.utoronto.ca", "student_id": "adebayob", "source": "N/A", "student_number": "0000000000"}], "results": {"unittest.loader.ModuleImportFailure": {"errors": {"unittest.loader.ModuleImportFailure.test_is_regex": {"description": "", "message": "Failed to import test module: test_is_regex\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_is_regex.py\", line 3, in <module>\n    from regex_functions import *\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 32, in testFailure\n    raise exception\n\nImportError: Failed to import test module: test_is_regex\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_is_regex.py\", line 3, in <module>\n    from regex_functions import *\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n\n"}, "unittest.loader.ModuleImportFailure.test_build_regex_tree": {"description": "", "message": "Failed to import test module: test_build_regex_tree\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_build_regex_tree.py\", line 3, in <module>\n    from regex_functions import *\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 32, in testFailure\n    raise exception\n\nImportError: Failed to import test module: test_build_regex_tree\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_build_regex_tree.py\", line 3, in <module>\n    from regex_functions import *\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n\n"}, "unittest.loader.ModuleImportFailure.test_regex_match": {"description": "", "message": "Failed to import test module: test_regex_match\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_regex_match.py\", line 3, in <module>\n    from regex_functions import *\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 32, in testFailure\n    raise exception\n\nImportError: Failed to import test module: test_regex_match\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_regex_match.py\", line 3, in <module>\n    from regex_functions import *\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n\n"}, "unittest.loader.ModuleImportFailure.test_all_regex_perms": {"description": "", "message": "Failed to import test module: test_all_regex_perms\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_all_regex_perms.py\", line 4, in <module>\n    from regex_functions import *\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 32, in testFailure\n    raise exception\n\nImportError: Failed to import test module: test_all_regex_perms\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_all_regex_perms.py\", line 4, in <module>\n    from regex_functions import *\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n\n"}, "unittest.loader.ModuleImportFailure.test_pep8": {"description": "", "message": "Failed to import test module: test_pep8\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_pep8.py\", line 3, in <module>\n    import regex_functions\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 32, in testFailure\n    raise exception\n\nImportError: Failed to import test module: test_pep8\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/adebayob/a2/test_pep8.py\", line 3, in <module>\n    import regex_functions\n  File \"/home/a08test/submissions/adebayob/a2/regex_functions.py\", line 23\n    from\u00a0regextree\u00a0import\u00a0RegexTree,\u00a0StarTree,\u00a0DotTree,\u00a0BarTree,\u00a0Leaf\n        \u00a0         \u00a0      \u00a0        ^\nSyntaxError: invalid character in identifier\n\n"}}}}, "date": "2016-04-01T02:39:24"}