Autotested Results for a1p2 submitted by Babatope Adebayo (adebayob)
Generated at 2016-03-12T23:59:30

Summary of Results: 4 out of 44 tests successfully passed
--

Tests for test_a1.TestA1 (3/43 passed)
--

1) test_a1.TestA1.test_init                                                           .. ok!
2) test_a1.TestA1.test_set_val_index_error                                            .. ok!
3) test_a1.TestA1.test_get_val_index_error                                            .. ok!
4) test_a1.TestA1.test_get_col_type                                                   .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 231, in test_get_col_type
        self.assertTrue(isinstance(m.get_col(1), a1.OneDimensionalMatrix), "get_col not returning a OneDimensionalMatrix")
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 157, in get_col
        res.set_val(i, 0, self.get_val(i, col_num - 1))
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

5) test_a1.TestA1.test_get_col_1d                                                     .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 239, in test_get_col_1d
        m.set_val(1, 1, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

6) test_a1.TestA1.test_get_row_set_col                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 305, in test_get_row_set_col
        m.set_val(1, 2, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

7) test_a1.TestA1.test_transpose                                                      .. error
.. because __init__() missing 1 required positional argument: 'n' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 467, in test_transpose
        m1 = a1.SquareMatrix(3)
    
    TypeError: __init__() missing 1 required positional argument: 'n'

8) test_a1.TestA1.test_matrix_mult                                                    .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 423, in test_matrix_mult
        m1.set_val(0, 0, 1)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

9) test_a1.TestA1.test_add_matrix_dimensions                                          .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 413, in test_add_matrix_dimensions
        r = m1.add_matrix(m2)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 224, in add_matrix
        res.set_val(i, j, self.get_val(i, j) +
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

10) test_a1.TestA1.test_identity_invalid_2                                             .. error
.. because __init__() missing 1 required positional argument: 'n' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 557, in test_identity_invalid_2
        m = a1.IdentityMatrix(3)
    
    TypeError: __init__() missing 1 required positional argument: 'n'

11) test_a1.TestA1.test_get_row_values                                                 .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 253, in test_get_row_values
        m.set_val(1, 2, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

12) test_a1.TestA1.test_matrix_mult_dimensions                                         .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 457, in test_matrix_mult_dimensions
        r = m1.multiply_matrix(m2)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 237, in multiply_matrix
        res.set_val(i, j, self.get_val(i, j) *
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

13) test_a1.TestA1.test_set_val_default_nodes_2                                        .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 175, in test_set_val_default_nodes_2
        m.set_val(2, 2, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

14) test_a1.TestA1.test_set_val_deleting_nodes                                         .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 197, in test_set_val_deleting_nodes
        m.set_val(2, 2, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

15) test_a1.TestA1.test_set_val_default_nodes                                          .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 163, in test_set_val_default_nodes
        m.set_val(2, 2, 0)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

16) test_a1.TestA1.test_set_val_deleting_nodes_2                                       .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 209, in test_set_val_deleting_nodes_2
        m.set_val(2, 2, 0)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

17) test_a1.TestA1.test_add_scalar_2                                                   .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 331, in test_add_scalar_2
        m.set_val(1, 2, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

18) test_a1.TestA1.test_add_scalar_default_2                                           .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 355, in test_add_scalar_default_2
        m.add_scalar(9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 198, in add_scalar
        self.set_val(i, j, self.get_val(i, j) + add_value)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

19) test_a1.TestA1.test_add_scalar                                                     .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 321, in test_add_scalar
        m.add_scalar(9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 198, in add_scalar
        self.set_val(i, j, self.get_val(i, j) + add_value)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

20) test_a1.TestA1.test_set_val_nodes_3                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 116, in test_set_val_nodes_3
        m.set_val(2, 2, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

21) test_a1.TestA1.test_diagonal                                                       .. error
.. because __init__() missing 1 required positional argument: 'n' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 481, in test_diagonal
        m1 = a1.SquareMatrix(3)
    
    TypeError: __init__() missing 1 required positional argument: 'n'

22) test_a1.TestA1.test_identity_invalid                                               .. error
.. because __init__() missing 1 required positional argument: 'n' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 547, in test_identity_invalid
        m = a1.IdentityMatrix(3)
    
    TypeError: __init__() missing 1 required positional argument: 'n'

23) test_a1.TestA1.test_get_row_type                                                   .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 223, in test_get_row_type
        self.assertTrue(isinstance(m.get_row(1), a1.OneDimensionalMatrix), "get_row not returning a OneDimensionalMatrix")
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 136, in get_row
        res.set_val(0, i, self.get_val(row_num - 1, i))
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

24) test_a1.TestA1.test_diagonal_matrix                                                .. error
.. because __init__() missing 1 required positional argument: 'n' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 511, in test_diagonal_matrix
        m1 = a1.DiagonalMatrix(3)
    
    TypeError: __init__() missing 1 required positional argument: 'n'

25) test_a1.TestA1.test_add_scalar_default                                             .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 343, in test_add_scalar_default
        m.add_scalar(9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 198, in add_scalar
        self.set_val(i, j, self.get_val(i, j) + add_value)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

26) test_a1.TestA1.test_set_val                                                        .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 87, in test_set_val
        m.set_val(1, 1, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

27) test_a1.TestA1.test_add_matrix_defaults                                            .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 369, in test_add_matrix_defaults
        r = m1.add_matrix(m2)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 224, in add_matrix
        res.set_val(i, j, self.get_val(i, j) +
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

28) test_a1.TestA1.test_add_matrix_defaults_unchanged                                  .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 381, in test_add_matrix_defaults_unchanged
        r = m1.add_matrix(m2)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 224, in add_matrix
        res.set_val(i, j, self.get_val(i, j) +
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

29) test_a1.TestA1.test_get_val_default                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 67, in test_get_val_default
        self.assertEqual(m.get_val(1,1), 9, "Matrix created with default value not returning that value for get_val")
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

30) test_a1.TestA1.test_set_val_nodes_8                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 155, in test_set_val_nodes_8
        m.set_val(2, 0, 11)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

31) test_a1.TestA1.test_set_val_nodes_6                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 141, in test_set_val_nodes_6
        m.set_val(0, 2, 11)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

32) test_a1.TestA1.test_set_val_nodes_7                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 148, in test_set_val_nodes_7
        m.set_val(1, 0, 11)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

33) test_a1.TestA1.test_set_val_nodes_4                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 126, in test_set_val_nodes_4
        m.set_val(2, 2, 11)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

34) test_a1.TestA1.test_set_val_nodes_5                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 133, in test_set_val_nodes_5
        m.set_val(0, 1, 11)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

35) test_a1.TestA1.test_set_val_nodes_2                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 106, in test_set_val_nodes_2
        m.set_val(2, 1, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

36) test_a1.TestA1.test_get_set_row                                                    .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 291, in test_get_set_row
        m.set_val(2, 1, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

37) test_a1.TestA1.test_set_val_nodes_1                                                .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 97, in test_set_val_nodes_1
        m.set_val(2, 2, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

38) test_a1.TestA1.test_add_matrix_set_nodes                                           .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 395, in test_add_matrix_set_nodes
        m1.set_val(1, 1, 1)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

39) test_a1.TestA1.test_diagonal_invalid                                               .. error
.. because __init__() missing 1 required positional argument: 'n' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 525, in test_diagonal_invalid
        m = a1.DiagonalMatrix(3)
    
    TypeError: __init__() missing 1 required positional argument: 'n'

40) test_a1.TestA1.test_symmetric_matrix                                               .. error
.. because __init__() missing 1 required positional argument: 'n' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 499, in test_symmetric_matrix
        m1 = a1.SymmetricMatrix(3)
    
    TypeError: __init__() missing 1 required positional argument: 'n'

41) test_a1.TestA1.test_identity                                                       .. error
.. because __init__() missing 1 required positional argument: 'n' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 535, in test_identity
        m = a1.IdentityMatrix(3)
    
    TypeError: __init__() missing 1 required positional argument: 'n'

42) test_a1.TestA1.test_get_col_values                                                 .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 265, in test_get_col_values
        m.set_val(2, 1, 9)
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 125, in set_val
        node = self.get_node(i, j).se
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 109, in get_node
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'

43) test_a1.TestA1.test_get_val                                                        .. error
.. because 'NoneType' object has no attribute 'get_down' (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/adebayob/a1p2/test_a1.py", line 59, in test_get_val
        self.assertEqual(m.get_val(1, 1), 0, "Empty matrix with no default should have all 0s")
    
      File "/home/a08test/submissions/adebayob/a1p2/a1.py", line 89, in get_val
        node = self._head.get_right().get_down()
    
    AttributeError: 'NoneType' object has no attribute 'get_down'



Tests for test_pep8.Test (1/1 passed)
--

1) test_pep8.Test.test_pep8                                                           .. ok!


