{"results": {"test_pep8.Test": {"passes": {"test_pep8.Test.test_pep8": ""}}, "test_a1.TestA1": {"errors": {"test_a1.TestA1.test_set_val_nodes_6": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 141, in test_set_val_nodes_6\n    m.set_val(0, 2, 11)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_add_scalar_2": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 331, in test_add_scalar_2\n    m.set_val(1, 2, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_get_col_type": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 231, in test_get_col_type\n    self.assertTrue(isinstance(m.get_col(1), a1.OneDimensionalMatrix), \"get_col not returning a OneDimensionalMatrix\")\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 157, in get_col\n    res.set_val(i, 0, self.get_val(i, col_num - 1))\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_deleting_nodes": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 197, in test_set_val_deleting_nodes\n    m.set_val(2, 2, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_add_matrix_set_nodes": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 395, in test_add_matrix_set_nodes\n    m1.set_val(1, 1, 1)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_diagonal_invalid": {"message": "__init__() missing 1 required positional argument: 'n'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 525, in test_diagonal_invalid\n    m = a1.DiagonalMatrix(3)\n\nTypeError: __init__() missing 1 required positional argument: 'n'\n"}, "test_a1.TestA1.test_set_val_nodes_8": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 155, in test_set_val_nodes_8\n    m.set_val(2, 0, 11)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_add_matrix_dimensions": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 413, in test_add_matrix_dimensions\n    r = m1.add_matrix(m2)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 224, in add_matrix\n    res.set_val(i, j, self.get_val(i, j) +\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_identity_invalid_2": {"message": "__init__() missing 1 required positional argument: 'n'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 557, in test_identity_invalid_2\n    m = a1.IdentityMatrix(3)\n\nTypeError: __init__() missing 1 required positional argument: 'n'\n"}, "test_a1.TestA1.test_get_row_set_col": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 305, in test_get_row_set_col\n    m.set_val(1, 2, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_nodes_4": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 126, in test_set_val_nodes_4\n    m.set_val(2, 2, 11)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_transpose": {"message": "__init__() missing 1 required positional argument: 'n'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 467, in test_transpose\n    m1 = a1.SquareMatrix(3)\n\nTypeError: __init__() missing 1 required positional argument: 'n'\n"}, "test_a1.TestA1.test_add_scalar_default": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 343, in test_add_scalar_default\n    m.add_scalar(9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 198, in add_scalar\n    self.set_val(i, j, self.get_val(i, j) + add_value)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_nodes_7": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 148, in test_set_val_nodes_7\n    m.set_val(1, 0, 11)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_default_nodes": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 163, in test_set_val_default_nodes\n    m.set_val(2, 2, 0)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_deleting_nodes_2": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 209, in test_set_val_deleting_nodes_2\n    m.set_val(2, 2, 0)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 87, in test_set_val\n    m.set_val(1, 1, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_add_matrix_defaults": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 369, in test_add_matrix_defaults\n    r = m1.add_matrix(m2)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 224, in add_matrix\n    res.set_val(i, j, self.get_val(i, j) +\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_add_matrix_defaults_unchanged": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 381, in test_add_matrix_defaults_unchanged\n    r = m1.add_matrix(m2)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 224, in add_matrix\n    res.set_val(i, j, self.get_val(i, j) +\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_get_col_values": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 265, in test_get_col_values\n    m.set_val(2, 1, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_nodes_1": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 97, in test_set_val_nodes_1\n    m.set_val(2, 2, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_matrix_mult": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 423, in test_matrix_mult\n    m1.set_val(0, 0, 1)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_add_scalar_default_2": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 355, in test_add_scalar_default_2\n    m.add_scalar(9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 198, in add_scalar\n    self.set_val(i, j, self.get_val(i, j) + add_value)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_nodes_5": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 133, in test_set_val_nodes_5\n    m.set_val(0, 1, 11)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_get_set_row": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 291, in test_get_set_row\n    m.set_val(2, 1, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_get_row_values": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 253, in test_get_row_values\n    m.set_val(1, 2, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_matrix_mult_dimensions": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 457, in test_matrix_mult_dimensions\n    r = m1.multiply_matrix(m2)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 237, in multiply_matrix\n    res.set_val(i, j, self.get_val(i, j) *\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_diagonal": {"message": "__init__() missing 1 required positional argument: 'n'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 481, in test_diagonal\n    m1 = a1.SquareMatrix(3)\n\nTypeError: __init__() missing 1 required positional argument: 'n'\n"}, "test_a1.TestA1.test_get_row_type": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 223, in test_get_row_type\n    self.assertTrue(isinstance(m.get_row(1), a1.OneDimensionalMatrix), \"get_row not returning a OneDimensionalMatrix\")\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 136, in get_row\n    res.set_val(0, i, self.get_val(row_num - 1, i))\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_identity_invalid": {"message": "__init__() missing 1 required positional argument: 'n'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 547, in test_identity_invalid\n    m = a1.IdentityMatrix(3)\n\nTypeError: __init__() missing 1 required positional argument: 'n'\n"}, "test_a1.TestA1.test_get_val": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 59, in test_get_val\n    self.assertEqual(m.get_val(1, 1), 0, \"Empty matrix with no default should have all 0s\")\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_nodes_3": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 116, in test_set_val_nodes_3\n    m.set_val(2, 2, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_get_col_1d": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 239, in test_get_col_1d\n    m.set_val(1, 1, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_identity": {"message": "__init__() missing 1 required positional argument: 'n'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 535, in test_identity\n    m = a1.IdentityMatrix(3)\n\nTypeError: __init__() missing 1 required positional argument: 'n'\n"}, "test_a1.TestA1.test_symmetric_matrix": {"message": "__init__() missing 1 required positional argument: 'n'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 499, in test_symmetric_matrix\n    m1 = a1.SymmetricMatrix(3)\n\nTypeError: __init__() missing 1 required positional argument: 'n'\n"}, "test_a1.TestA1.test_add_scalar": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 321, in test_add_scalar\n    m.add_scalar(9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 198, in add_scalar\n    self.set_val(i, j, self.get_val(i, j) + add_value)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_default_nodes_2": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 175, in test_set_val_default_nodes_2\n    m.set_val(2, 2, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_set_val_nodes_2": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 106, in test_set_val_nodes_2\n    m.set_val(2, 1, 9)\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 125, in set_val\n    node = self.get_node(i, j).se\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 109, in get_node\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}, "test_a1.TestA1.test_diagonal_matrix": {"message": "__init__() missing 1 required positional argument: 'n'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 511, in test_diagonal_matrix\n    m1 = a1.DiagonalMatrix(3)\n\nTypeError: __init__() missing 1 required positional argument: 'n'\n"}, "test_a1.TestA1.test_get_val_default": {"message": "'NoneType' object has no attribute 'get_down'", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/adebayob/a1p2/test_a1.py\", line 67, in test_get_val_default\n    self.assertEqual(m.get_val(1,1), 9, \"Matrix created with default value not returning that value for get_val\")\n\n  File \"/home/a08test/submissions/adebayob/a1p2/a1.py\", line 89, in get_val\n    node = self._head.get_right().get_down()\n\nAttributeError: 'NoneType' object has no attribute 'get_down'\n"}}, "passes": {"test_a1.TestA1.test_get_val_index_error": "", "test_a1.TestA1.test_set_val_index_error": "", "test_a1.TestA1.test_init": ""}}}, "origin": "/home/a08test/submissions/adebayob/a1p2", "date": "2016-03-12T23:59:30", "assignment": "a1p2", "students": [{"student_id": "adebayob", "email": "tope.adebayo@mail.utoronto.ca", "last": "Adebayo", "source": "N/A", "first": "Babatope", "student_number": "0000000000", "section": "N/A"}]}