Autotested Results for a2 submitted by Aleem Ahmad (ahmadale)
Generated at 2016-04-01T02:39:24

Summary of Results: 10 out of 44 tests successfully passed
--

Tests for test_is_regex.TestIsRegex (6/16 passed)
--

1) Dot-star-like non-regexes rejected?                                                .. ok!
2) Bar-dot-line non-regexes rejected?                                                 .. ok!
3) Bar-like non-regexes rejected?                                                     .. ok!
4) Dot-like non-regexes rejected?                                                     .. ok!
5) Bar-star-dot non-regexes rejected?                                                 .. ok!
6) Bar-star-like non-regexes rejected?                                                .. ok!
7) Star regexes accepted?                                                             .. failed
.. because False is not true : Rejects valid regex: e* (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 66, in test_star_ok
        "Rejects valid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid regex: e*

8) Bar-dot regexes accepted?                                                          .. failed
.. because False is not true : Rejects valid regex: ((0.1)|(2.e)) (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 82, in test_bar_dot_ok
        "Rejects valid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid regex: ((0.1)|(2.e))

9) Leaf non-regexes rejected?                                                         .. failed
.. because True is not false : Accepts invalid regex: 00 (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 31, in test_leaf_fail
        "Accepts invalid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 648, in assertFalse
        raise self.failureException(msg)
    
    AssertionError: True is not false : Accepts invalid regex: 00

10) Bar-star-dot regexes accepted?                                                     .. failed
.. because False is not true : Rejects valid regex: ((0.e)|(1*.2))* (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 128, in test_bar_star_dot_ok
        "Rejects valid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid regex: ((0.e)|(1*.2))*

11) Leaf regular expressions accepted?                                                 .. failed
.. because False is not true : Rejects valid regex: e (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 24, in test_leaf_ok
        "Rejects valid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid regex: e

12) Star-like non-regexes rejected?                                                    .. failed
.. because True is not false : Accepts invalid regex: *1 (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 73, in test_star_fail
        "Accepts invalid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 648, in assertFalse
        raise self.failureException(msg)
    
    AssertionError: True is not false : Accepts invalid regex: *1

13) Bar regexes accepted?                                                              .. failed
.. because False is not true : Rejects valid regex: (0|1) (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 38, in test_bar
        "Rejects valid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid regex: (0|1)

14) Dot regexes accepted?                                                              .. failed
.. because False is not true : Rejects valid regex: (0.1) (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 52, in test_dot
        "Rejects valid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid regex: (0.1)

15) Bar-star regexes accepted?                                                         .. failed
.. because False is not true : Rejects valid regex: (0|1)* (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 97, in test_bar_star_ok
        "Rejects valid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid regex: (0|1)*

16) Dot-star regexes accepted?                                                         .. failed
.. because False is not true : Rejects valid regex: (0.1)* (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_is_regex.py", line 112, in test_dot_star_ok
        "Rejects valid regex: {}".format(r))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid regex: (0.1)*



Tests for test_regex_match.TestRegexMatch (4/18 passed)
--

1) Correctly rejects near-bars?                                                       .. ok!
2) Correctly rejects near-dots?                                                       .. ok!
3) Correct rejects near-leaves?                                                       .. ok!
4) Correctly rejects near dot-bars?                                                   .. ok!
5) Correctly matches various matches of empty string?                                 .. failed
.. because False is not true : Rejects valid match: (DotTree(Leaf('e'), Leaf('e')), '') (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 46, in test_edge_empty_ok
        "Rejects valid match: {}".format(t))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid match: (DotTree(Leaf('e'), Leaf('e')), '')

6) Correctly matches leaf regexes?                                                    .. failed
.. because False is not true : Rejects valid match: (Leaf('e'), '') (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 30, in test_leaf_ok
        "Rejects valid match: {}".format(t))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid match: (Leaf('e'), '')

7) Correctly matches dot-bar regexes?                                                 .. failed
.. because False is not true : Rejects valid match: (DotTree(BarTree(Leaf('0'), Leaf('1')), BarTree(Leaf('2'), Leaf('0'))), '12') (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 103, in test_dot_bar_ok
        "Rejects valid match: {}".format(t))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid match: (DotTree(BarTree(Leaf('0'), Leaf('1')), BarTree(Leaf('2'), Leaf('0'))), '12')

8) Correctly matches dotted regexes?                                                  .. failed
.. because False is not true : Rejects valid match: (DotTree(Leaf('1'), Leaf('e')), '1') (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 54, in test_dot_okay
        "Rejects valid match: {}".format(t))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid match: (DotTree(Leaf('1'), Leaf('e')), '1')

9) Correctly matches barred regexes?                                                  .. failed
.. because False is not true : Rejects valid match: (BarTree(Leaf('1'), Leaf('e')), '1') (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 70, in test_bar_okay
        "Rejects valid match: {}".format(t))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid match: (BarTree(Leaf('1'), Leaf('e')), '1')

10) Correctly matches bar-star-dot regexes?                                            .. failed
.. because False is not true : Rejects valid match: (BarTree(StarTree(Leaf('2')), DotTree(Leaf('1'), Leaf('0'))), '10') (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 157, in test_bar_star_dot_ok
        "Rejects valid match: {}".format(t))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : Rejects valid match: (BarTree(StarTree(Leaf('2')), DotTree(Leaf('1'), Leaf('0'))), '10')

11) Correctly rejects near dot-stars?                                                  .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 130, in test_dot_star_fail
        self.assertFalse(regex_match(t[0], t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 50, in regex_match
        is_right = regex_match(r._children[1], i)
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 49, in regex_match
        elif r._children[1] is not None:
    
    IndexError: list index out of range

12) Correctly rejects near bar-star-dots?                                              .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 166, in test_bar_star_dot_fail
        self.assertFalse(regex_match(t[0], t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 50, in regex_match
        is_right = regex_match(r._children[1], i)
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 49, in regex_match
        elif r._children[1] is not None:
    
    IndexError: list index out of range

13) Correctly rejects near bar-stars?                                                  .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 146, in test_bar_star_fail
        self.assertFalse(regex_match(t[0], t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 50, in regex_match
        is_right = regex_match(r._children[1], i)
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 49, in regex_match
        elif r._children[1] is not None:
    
    IndexError: list index out of range

14) Correctly rejects near-stars?                                                      .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 92, in test_star_fail
        self.assertFalse(regex_match(t[0], t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 49, in regex_match
        elif r._children[1] is not None:
    
    IndexError: list index out of range

15) Correct on difficult case for star (1|(1.2))*?                                     .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 177, in test_difficult_star
        self.assertTrue(regex_match(r,s),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 49, in regex_match
        elif r._children[1] is not None:
    
    IndexError: list index out of range

16) Correctly matches dot-star regexes?                                                .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 122, in test_dot_star_ok
        self.assertTrue(regex_match(t[0], t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 50, in regex_match
        is_right = regex_match(r._children[1], i)
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 49, in regex_match
        elif r._children[1] is not None:
    
    IndexError: list index out of range

17) Correctly matches bar-star regexes?                                                .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 138, in test_bar_star_ok
        self.assertTrue(regex_match(t[0], t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 50, in regex_match
        is_right = regex_match(r._children[1], i)
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 49, in regex_match
        elif r._children[1] is not None:
    
    IndexError: list index out of range

18) Correctly matches starred regexes?                                                 .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_regex_match.py", line 84, in test_star_okay
        self.assertTrue(regex_match(t[0], t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 49, in regex_match
        elif r._children[1] is not None:
    
    IndexError: list index out of range



Tests for test_build_regex_tree.TestBuildRegexTree (0/5 passed)
--

1) Correctly builds bar trees?                                                        .. failed
.. because BarTree(Leaf('0'), Leaf('1')) != BarTree('0', '1') : Regex tree BarTree(Leaf('0'), Leaf('1')) doesn't match (0|1). (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py", line 43, in test_bar
        t[0], t[1]))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 797, in assertEqual
        assertion_func(first, second, msg=msg)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 790, in _baseAssertEqual
        raise self.failureException(msg)
    
    AssertionError: BarTree(Leaf('0'), Leaf('1')) != BarTree('0', '1') : Regex tree BarTree(Leaf('0'), Leaf('1')) doesn't match (0|1).

2) Correctly builds dot trees?                                                        .. failed
.. because DotTree(Leaf('0'), Leaf('1')) != DotTree('0', '1') : Regex tree DotTree(Leaf('0'), Leaf('1')) doesn't match (0.1). (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py", line 34, in test_dot
        t[0], t[1]))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 797, in assertEqual
        assertion_func(first, second, msg=msg)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 790, in _baseAssertEqual
        raise self.failureException(msg)
    
    AssertionError: DotTree(Leaf('0'), Leaf('1')) != DotTree('0', '1') : Regex tree DotTree(Leaf('0'), Leaf('1')) doesn't match (0.1).

3) Correctly builds bar-dot trees?                                                    .. failed
.. because BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) != BarTree(['0', '1'], '.') : Regex tree BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) doesn't match ((0.1)|(2.e)). (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py", line 66, in test_bar_dot
        t[0], t[1]))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 797, in assertEqual
        assertion_func(first, second, msg=msg)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 790, in _baseAssertEqual
        raise self.failureException(msg)
    
    AssertionError: BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) != BarTree(['0', '1'], '.') : Regex tree BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) doesn't match ((0.1)|(2.e)).

4) Correctly builds leaves?                                                           .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py", line 23, in test_leaf
        self.assertEqual(t[0], build_regex_tree(t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 173, in build_regex_tree
        if ret[1] == '|':
    
    IndexError: list index out of range

5) Correctly builds star trees?                                                       .. error
.. because list index out of range (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py", line 49, in test_star
        self.assertEqual(t[0], build_regex_tree(t[1]),
    
      File "/home/a08test/submissions/ahmadale/a2/regex_functions.py", line 173, in build_regex_tree
        if ret[1] == '|':
    
    IndexError: list index out of range



Tests for test_all_regex_perms.TestAllRegexPermutations (0/4 passed)
--

1) Correctly produces unique permutation of leaf?                                     .. failed
.. because {'e'} != [] : Different permutation set: {'e'}, [] (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_all_regex_perms.py", line 30, in test_leaf
        set(s), all_regex_permutations(s)))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 797, in assertEqual
        assertion_func(first, second, msg=msg)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 790, in _baseAssertEqual
        raise self.failureException(msg)
    
    AssertionError: {'e'} != [] : Different permutation set: {'e'}, []

2) Correctly produces permutations of binary regexes?                                 .. failed
.. because [] != {'(0.1)', '(1.0)'} : Different permutation sets: [], {'(0.1)', '(1.0)'} (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_all_regex_perms.py", line 41, in test_binary
        all_regex_permutations(t[0]), t[1]))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 797, in assertEqual
        assertion_func(first, second, msg=msg)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 790, in _baseAssertEqual
        raise self.failureException(msg)
    
    AssertionError: [] != {'(0.1)', '(1.0)'} : Different permutation sets: [], {'(0.1)', '(1.0)'}

3) test_all_regex_perms.TestAllRegexPermutations.test_empty_results                   .. failed
.. because False is not true : No regular expressions can be formed from 0221 but returned a non-empty collection (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_all_regex_perms.py", line 22, in test_empty_results
        " but returned a non-empty collection").format(s))
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 654, in assertTrue
        raise self.failureException(msg)
    
    AssertionError: False is not true : No regular expressions can be formed from 0221 but returned a non-empty collection

4) Correctly produces permutations of long regex?                                     .. failed
.. because [] != {'(0*.1*)', '(0**.1)', '(1.0*)*', '(0.1*)[86 chars]0)*'} (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_all_regex_perms.py", line 50, in test_long
        self.assertEqual(all_regex_permutations(s), p)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 797, in assertEqual
        assertion_func(first, second, msg=msg)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 790, in _baseAssertEqual
        raise self.failureException(msg)
    
    AssertionError: [] != {'(0*.1*)', '(0**.1)', '(1.0*)*', '(0.1*)[86 chars]0)*'}



Tests for test_pep8.TestPEP8 (0/1 passed)
--

1) test_pep8.TestPEP8.test_pep8                                                       .. failed
.. because 51 != 0 : Found code style errors (and warnings):
E302: expected 2 blank lines, found 1 (7)
E265: block comment should start with '# ' (38)
E231: missing whitespace after ',' (3)
E225: missing whitespace around operator (3) (details below):

    Traceback (most recent call last):
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
        yield
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 577, in run
        testMethod()
    
      File "/home/a08test/submissions/ahmadale/a2/test_pep8.py", line 19, in test_pep8
        self.assertEqual(result.total_errors, 0, report_output)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 797, in assertEqual
        assertion_func(first, second, msg=msg)
    
      File "/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py", line 790, in _baseAssertEqual
        raise self.failureException(msg)
    
    AssertionError: 51 != 0 : Found code style errors (and warnings):
    E302: expected 2 blank lines, found 1 (7)
    E265: block comment should start with '# ' (38)
    E231: missing whitespace after ',' (3)
    E225: missing whitespace around operator (3)



