{"origin": "/home/a08test/submissions/ahmadale/a2", "assignment": "a2", "students": [{"last": "Ahmad", "section": "N/A", "first": "Aleem", "email": "aleem.ahmad@mail.utoronto.ca", "student_id": "ahmadale", "source": "N/A", "student_number": "0000000000"}], "results": {"test_pep8.TestPEP8": {"failures": {"test_pep8.TestPEP8.test_pep8": {"description": "", "message": "51 != 0 : Found code style errors (and warnings):\nE302: expected 2 blank lines, found 1 (7)\nE265: block comment should start with '# ' (38)\nE231: missing whitespace after ',' (3)\nE225: missing whitespace around operator (3)", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_pep8.py\", line 19, in test_pep8\n    self.assertEqual(result.total_errors, 0, report_output)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: 51 != 0 : Found code style errors (and warnings):\nE302: expected 2 blank lines, found 1 (7)\nE265: block comment should start with '# ' (38)\nE231: missing whitespace after ',' (3)\nE225: missing whitespace around operator (3)\n"}}}, "test_all_regex_perms.TestAllRegexPermutations": {"failures": {"test_all_regex_perms.TestAllRegexPermutations.test_long": {"description": "Correctly produces permutations of long regex?", "message": "[] != {'(0*.1*)', '(0**.1)', '(1.0*)*', '(0.1*)[86 chars]0)*'}", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_all_regex_perms.py\", line 50, in test_long\n    self.assertEqual(all_regex_permutations(s), p)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: [] != {'(0*.1*)', '(0**.1)', '(1.0*)*', '(0.1*)[86 chars]0)*'}\n"}, "test_all_regex_perms.TestAllRegexPermutations.test_binary": {"description": "Correctly produces permutations of binary regexes?", "message": "[] != {'(0.1)', '(1.0)'} : Different permutation sets: [], {'(0.1)', '(1.0)'}", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_all_regex_perms.py\", line 41, in test_binary\n    all_regex_permutations(t[0]), t[1]))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: [] != {'(0.1)', '(1.0)'} : Different permutation sets: [], {'(0.1)', '(1.0)'}\n"}, "test_all_regex_perms.TestAllRegexPermutations.test_empty_results": {"description": "", "message": "False is not true : No regular expressions can be formed from 0221 but returned a non-empty collection", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_all_regex_perms.py\", line 22, in test_empty_results\n    \" but returned a non-empty collection\").format(s))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : No regular expressions can be formed from 0221 but returned a non-empty collection\n"}, "test_all_regex_perms.TestAllRegexPermutations.test_leaf": {"description": "Correctly produces unique permutation of leaf?", "message": "{'e'} != [] : Different permutation set: {'e'}, []", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_all_regex_perms.py\", line 30, in test_leaf\n    set(s), all_regex_permutations(s)))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: {'e'} != [] : Different permutation set: {'e'}, []\n"}}}, "test_regex_match.TestRegexMatch": {"passes": {"test_regex_match.TestRegexMatch.test_dot_bar_fail": "Correctly rejects near dot-bars?", "test_regex_match.TestRegexMatch.test_bar_fail": "Correctly rejects near-bars?", "test_regex_match.TestRegexMatch.test_dot_fail": "Correctly rejects near-dots?", "test_regex_match.TestRegexMatch.test_leaf_fail": "Correct rejects near-leaves?"}, "errors": {"test_regex_match.TestRegexMatch.test_bar_star_fail": {"description": "Correctly rejects near bar-stars?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 146, in test_bar_star_fail\n    self.assertFalse(regex_match(t[0], t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 50, in regex_match\n    is_right = regex_match(r._children[1], i)\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 49, in regex_match\n    elif r._children[1] is not None:\n\nIndexError: list index out of range\n"}, "test_regex_match.TestRegexMatch.test_bar_star_dot_fail": {"description": "Correctly rejects near bar-star-dots?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 166, in test_bar_star_dot_fail\n    self.assertFalse(regex_match(t[0], t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 50, in regex_match\n    is_right = regex_match(r._children[1], i)\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 49, in regex_match\n    elif r._children[1] is not None:\n\nIndexError: list index out of range\n"}, "test_regex_match.TestRegexMatch.test_difficult_star": {"description": "Correct on difficult case for star (1|(1.2))*?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 177, in test_difficult_star\n    self.assertTrue(regex_match(r,s),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 49, in regex_match\n    elif r._children[1] is not None:\n\nIndexError: list index out of range\n"}, "test_regex_match.TestRegexMatch.test_dot_star_ok": {"description": "Correctly matches dot-star regexes?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 122, in test_dot_star_ok\n    self.assertTrue(regex_match(t[0], t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 50, in regex_match\n    is_right = regex_match(r._children[1], i)\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 49, in regex_match\n    elif r._children[1] is not None:\n\nIndexError: list index out of range\n"}, "test_regex_match.TestRegexMatch.test_bar_star_ok": {"description": "Correctly matches bar-star regexes?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 138, in test_bar_star_ok\n    self.assertTrue(regex_match(t[0], t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 50, in regex_match\n    is_right = regex_match(r._children[1], i)\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 49, in regex_match\n    elif r._children[1] is not None:\n\nIndexError: list index out of range\n"}, "test_regex_match.TestRegexMatch.test_dot_star_fail": {"description": "Correctly rejects near dot-stars?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 130, in test_dot_star_fail\n    self.assertFalse(regex_match(t[0], t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 50, in regex_match\n    is_right = regex_match(r._children[1], i)\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 49, in regex_match\n    elif r._children[1] is not None:\n\nIndexError: list index out of range\n"}, "test_regex_match.TestRegexMatch.test_star_okay": {"description": "Correctly matches starred regexes?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 84, in test_star_okay\n    self.assertTrue(regex_match(t[0], t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 49, in regex_match\n    elif r._children[1] is not None:\n\nIndexError: list index out of range\n"}, "test_regex_match.TestRegexMatch.test_star_fail": {"description": "Correctly rejects near-stars?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 92, in test_star_fail\n    self.assertFalse(regex_match(t[0], t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 49, in regex_match\n    elif r._children[1] is not None:\n\nIndexError: list index out of range\n"}}, "failures": {"test_regex_match.TestRegexMatch.test_dot_okay": {"description": "Correctly matches dotted regexes?", "message": "False is not true : Rejects valid match: (DotTree(Leaf('1'), Leaf('e')), '1')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 54, in test_dot_okay\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (DotTree(Leaf('1'), Leaf('e')), '1')\n"}, "test_regex_match.TestRegexMatch.test_bar_okay": {"description": "Correctly matches barred regexes?", "message": "False is not true : Rejects valid match: (BarTree(Leaf('1'), Leaf('e')), '1')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 70, in test_bar_okay\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (BarTree(Leaf('1'), Leaf('e')), '1')\n"}, "test_regex_match.TestRegexMatch.test_bar_star_dot_ok": {"description": "Correctly matches bar-star-dot regexes?", "message": "False is not true : Rejects valid match: (BarTree(StarTree(Leaf('2')), DotTree(Leaf('1'), Leaf('0'))), '10')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 157, in test_bar_star_dot_ok\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (BarTree(StarTree(Leaf('2')), DotTree(Leaf('1'), Leaf('0'))), '10')\n"}, "test_regex_match.TestRegexMatch.test_edge_empty_ok": {"description": "Correctly matches various matches of empty string?", "message": "False is not true : Rejects valid match: (DotTree(Leaf('e'), Leaf('e')), '')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 46, in test_edge_empty_ok\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (DotTree(Leaf('e'), Leaf('e')), '')\n"}, "test_regex_match.TestRegexMatch.test_leaf_ok": {"description": "Correctly matches leaf regexes?", "message": "False is not true : Rejects valid match: (Leaf('e'), '')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 30, in test_leaf_ok\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (Leaf('e'), '')\n"}, "test_regex_match.TestRegexMatch.test_dot_bar_ok": {"description": "Correctly matches dot-bar regexes?", "message": "False is not true : Rejects valid match: (DotTree(BarTree(Leaf('0'), Leaf('1')), BarTree(Leaf('2'), Leaf('0'))), '12')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_regex_match.py\", line 103, in test_dot_bar_ok\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (DotTree(BarTree(Leaf('0'), Leaf('1')), BarTree(Leaf('2'), Leaf('0'))), '12')\n"}}}, "test_build_regex_tree.TestBuildRegexTree": {"errors": {"test_build_regex_tree.TestBuildRegexTree.test_star": {"description": "Correctly builds star trees?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py\", line 49, in test_star\n    self.assertEqual(t[0], build_regex_tree(t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 173, in build_regex_tree\n    if ret[1] == '|':\n\nIndexError: list index out of range\n"}, "test_build_regex_tree.TestBuildRegexTree.test_leaf": {"description": "Correctly builds leaves?", "message": "list index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py\", line 23, in test_leaf\n    self.assertEqual(t[0], build_regex_tree(t[1]),\n\n  File \"/home/a08test/submissions/ahmadale/a2/regex_functions.py\", line 173, in build_regex_tree\n    if ret[1] == '|':\n\nIndexError: list index out of range\n"}}, "failures": {"test_build_regex_tree.TestBuildRegexTree.test_bar_dot": {"description": "Correctly builds bar-dot trees?", "message": "BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) != BarTree(['0', '1'], '.') : Regex tree BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) doesn't match ((0.1)|(2.e)).", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py\", line 66, in test_bar_dot\n    t[0], t[1]))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) != BarTree(['0', '1'], '.') : Regex tree BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) doesn't match ((0.1)|(2.e)).\n"}, "test_build_regex_tree.TestBuildRegexTree.test_bar": {"description": "Correctly builds bar trees?", "message": "BarTree(Leaf('0'), Leaf('1')) != BarTree('0', '1') : Regex tree BarTree(Leaf('0'), Leaf('1')) doesn't match (0|1).", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py\", line 43, in test_bar\n    t[0], t[1]))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: BarTree(Leaf('0'), Leaf('1')) != BarTree('0', '1') : Regex tree BarTree(Leaf('0'), Leaf('1')) doesn't match (0|1).\n"}, "test_build_regex_tree.TestBuildRegexTree.test_dot": {"description": "Correctly builds dot trees?", "message": "DotTree(Leaf('0'), Leaf('1')) != DotTree('0', '1') : Regex tree DotTree(Leaf('0'), Leaf('1')) doesn't match (0.1).", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_build_regex_tree.py\", line 34, in test_dot\n    t[0], t[1]))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: DotTree(Leaf('0'), Leaf('1')) != DotTree('0', '1') : Regex tree DotTree(Leaf('0'), Leaf('1')) doesn't match (0.1).\n"}}}, "test_is_regex.TestIsRegex": {"passes": {"test_is_regex.TestIsRegex.test_bar_star_dot_fail": "Bar-star-dot non-regexes rejected?", "test_is_regex.TestIsRegex.test_dot_fail": "Dot-like non-regexes rejected?", "test_is_regex.TestIsRegex.test_dot_star_fail": "Dot-star-like non-regexes rejected?", "test_is_regex.TestIsRegex.test_bar_fail": "Bar-like non-regexes rejected?", "test_is_regex.TestIsRegex.test_bar_star_fail": "Bar-star-like non-regexes rejected?", "test_is_regex.TestIsRegex.test_bar_dot_fail": "Bar-dot-line non-regexes rejected?"}, "failures": {"test_is_regex.TestIsRegex.test_dot": {"description": "Dot regexes accepted?", "message": "False is not true : Rejects valid regex: (0.1)", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 52, in test_dot\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: (0.1)\n"}, "test_is_regex.TestIsRegex.test_leaf_ok": {"description": "Leaf regular expressions accepted?", "message": "False is not true : Rejects valid regex: e", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 24, in test_leaf_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: e\n"}, "test_is_regex.TestIsRegex.test_star_ok": {"description": "Star regexes accepted?", "message": "False is not true : Rejects valid regex: e*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 66, in test_star_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: e*\n"}, "test_is_regex.TestIsRegex.test_bar_star_dot_ok": {"description": "Bar-star-dot regexes accepted?", "message": "False is not true : Rejects valid regex: ((0.e)|(1*.2))*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 128, in test_bar_star_dot_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: ((0.e)|(1*.2))*\n"}, "test_is_regex.TestIsRegex.test_dot_star_ok": {"description": "Dot-star regexes accepted?", "message": "False is not true : Rejects valid regex: (0.1)*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 112, in test_dot_star_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: (0.1)*\n"}, "test_is_regex.TestIsRegex.test_bar_dot_ok": {"description": "Bar-dot regexes accepted?", "message": "False is not true : Rejects valid regex: ((0.1)|(2.e))", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 82, in test_bar_dot_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: ((0.1)|(2.e))\n"}, "test_is_regex.TestIsRegex.test_leaf_fail": {"description": "Leaf non-regexes rejected?", "message": "True is not false : Accepts invalid regex: 00", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 31, in test_leaf_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: 00\n"}, "test_is_regex.TestIsRegex.test_bar": {"description": "Bar regexes accepted?", "message": "False is not true : Rejects valid regex: (0|1)", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 38, in test_bar\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: (0|1)\n"}, "test_is_regex.TestIsRegex.test_bar_star_ok": {"description": "Bar-star regexes accepted?", "message": "False is not true : Rejects valid regex: (0|1)*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 97, in test_bar_star_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: (0|1)*\n"}, "test_is_regex.TestIsRegex.test_star_fail": {"description": "Star-like non-regexes rejected?", "message": "True is not false : Accepts invalid regex: *1", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadale/a2/test_is_regex.py\", line 73, in test_star_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: *1\n"}}}}, "date": "2016-04-01T02:39:24"}